<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ananda Vilar Vidal e José Jardel Alves de Medeiros">

<title>Relatório: base de dados pinguins</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Pinguins_Roteiro_files/libs/clipboard/clipboard.min.js"></script>
<script src="Pinguins_Roteiro_files/libs/quarto-html/quarto.js"></script>
<script src="Pinguins_Roteiro_files/libs/quarto-html/popper.min.js"></script>
<script src="Pinguins_Roteiro_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Pinguins_Roteiro_files/libs/quarto-html/anchor.min.js"></script>
<link href="Pinguins_Roteiro_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Pinguins_Roteiro_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Pinguins_Roteiro_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Pinguins_Roteiro_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Pinguins_Roteiro_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução"><span class="header-section-number">1</span> Introdução</a></li>
  <li><a href="#os-dados" id="toc-os-dados" class="nav-link" data-scroll-target="#os-dados"><span class="header-section-number">2</span> Os dados</a>
  <ul class="collapse">
  <li><a href="#análise-exploratória-dos-dados" id="toc-análise-exploratória-dos-dados" class="nav-link" data-scroll-target="#análise-exploratória-dos-dados"><span class="header-section-number">2.1</span> Análise exploratória dos dados</a></li>
  <li><a href="#análise-de-outliers" id="toc-análise-de-outliers" class="nav-link" data-scroll-target="#análise-de-outliers"><span class="header-section-number">2.2</span> Análise de outliers</a></li>
  <li><a href="#sec-GGally" id="toc-sec-GGally" class="nav-link" data-scroll-target="#sec-GGally"><span class="header-section-number">2.3</span> Análise de correlação</a>
  <ul class="collapse">
  <li><a href="#comentários" id="toc-comentários" class="nav-link" data-scroll-target="#comentários"><span class="header-section-number">2.3.1</span> Comentários:</a></li>
  <li><a href="#analisando-o-vif" id="toc-analisando-o-vif" class="nav-link" data-scroll-target="#analisando-o-vif"><span class="header-section-number">2.3.2</span> Analisando o VIF</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#modelos" id="toc-modelos" class="nav-link" data-scroll-target="#modelos"><span class="header-section-number">3</span> Modelos</a>
  <ul class="collapse">
  <li><a href="#modelo-1-com-todas-as-variáveis-independentes." id="toc-modelo-1-com-todas-as-variáveis-independentes." class="nav-link" data-scroll-target="#modelo-1-com-todas-as-variáveis-independentes."><span class="header-section-number">3.1</span> Modelo 1: Com todas as variáveis independentes.</a></li>
  <li><a href="#modelo-2-sem-a-variável-espécie." id="toc-modelo-2-sem-a-variável-espécie." class="nav-link" data-scroll-target="#modelo-2-sem-a-variável-espécie."><span class="header-section-number">3.2</span> Modelo 2: Sem a variável espécie.</a></li>
  <li><a href="#modelo-3-sem-as-variáveis-especie-e-ano." id="toc-modelo-3-sem-as-variáveis-especie-e-ano." class="nav-link" data-scroll-target="#modelo-3-sem-as-variáveis-especie-e-ano."><span class="header-section-number">3.3</span> Modelo 3: Sem as variáveis especie e ano.</a></li>
  <li><a href="#modelo-4-sem-as-variáveis-espécie-ano-e-comprimento_bico." id="toc-modelo-4-sem-as-variáveis-espécie-ano-e-comprimento_bico." class="nav-link" data-scroll-target="#modelo-4-sem-as-variáveis-espécie-ano-e-comprimento_bico."><span class="header-section-number">3.4</span> Modelo 4: Sem as variáveis espécie, ano e comprimento_bico.</a></li>
  </ul></li>
  <li><a href="#métodos-para-selecionar-o-melhor-modelo." id="toc-métodos-para-selecionar-o-melhor-modelo." class="nav-link" data-scroll-target="#métodos-para-selecionar-o-melhor-modelo."><span class="header-section-number">4</span> Métodos para selecionar o melhor modelo.</a>
  <ul class="collapse">
  <li><a href="#medida-aic" id="toc-medida-aic" class="nav-link" data-scroll-target="#medida-aic"><span class="header-section-number">4.1</span> Medida AIC</a></li>
  <li><a href="#medida-bic" id="toc-medida-bic" class="nav-link" data-scroll-target="#medida-bic"><span class="header-section-number">4.2</span> Medida BIC</a></li>
  <li><a href="#comparação-de-modelos-encaixados-anova" id="toc-comparação-de-modelos-encaixados-anova" class="nav-link" data-scroll-target="#comparação-de-modelos-encaixados-anova"><span class="header-section-number">4.3</span> Comparação de modelos encaixados (ANOVA)</a></li>
  </ul></li>
  <li><a href="#seleção-automática" id="toc-seleção-automática" class="nav-link" data-scroll-target="#seleção-automática"><span class="header-section-number">5</span> Seleção automática</a>
  <ul class="collapse">
  <li><a href="#a-partir-do-modelo-1" id="toc-a-partir-do-modelo-1" class="nav-link" data-scroll-target="#a-partir-do-modelo-1"><span class="header-section-number">5.1</span> A partir do modelo 1</a></li>
  <li><a href="#a-partir-do-modelo-2" id="toc-a-partir-do-modelo-2" class="nav-link" data-scroll-target="#a-partir-do-modelo-2"><span class="header-section-number">5.2</span> A partir do modelo 2</a></li>
  </ul></li>
  <li><a href="#modelo-selecionado-modelo4" id="toc-modelo-selecionado-modelo4" class="nav-link" data-scroll-target="#modelo-selecionado-modelo4"><span class="header-section-number">6</span> Modelo selecionado (modelo4)</a>
  <ul class="collapse">
  <li><a href="#verificando-os-pressupostos-do-mrlm" id="toc-verificando-os-pressupostos-do-mrlm" class="nav-link" data-scroll-target="#verificando-os-pressupostos-do-mrlm"><span class="header-section-number">6.1</span> Verificando os pressupostos do MRLM</a>
  <ul class="collapse">
  <li><a href="#análise-dos-pressupostos" id="toc-análise-dos-pressupostos" class="nav-link" data-scroll-target="#análise-dos-pressupostos"><span class="header-section-number">6.1.1</span> Análise dos pressupostos</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#interpretações-do-modelo-selecionado" id="toc-interpretações-do-modelo-selecionado" class="nav-link" data-scroll-target="#interpretações-do-modelo-selecionado"><span class="header-section-number">7</span> Interpretações do modelo selecionado</a>
  <ul class="collapse">
  <li><a href="#coeficientes-padronizados" id="toc-coeficientes-padronizados" class="nav-link" data-scroll-target="#coeficientes-padronizados"><span class="header-section-number">7.1</span> Coeficientes padronizados</a></li>
  </ul></li>
  <li><a href="#previsões" id="toc-previsões" class="nav-link" data-scroll-target="#previsões"><span class="header-section-number">8</span> Previsões</a>
  <ul class="collapse">
  <li><a href="#intervalo-de-confiança" id="toc-intervalo-de-confiança" class="nav-link" data-scroll-target="#intervalo-de-confiança"><span class="header-section-number">8.1</span> Intervalo de Confiança</a>
  <ul class="collapse">
  <li><a href="#interpretações" id="toc-interpretações" class="nav-link" data-scroll-target="#interpretações"><span class="header-section-number">8.1.1</span> Interpretações</a></li>
  </ul></li>
  <li><a href="#intervalo-de-previsão" id="toc-intervalo-de-previsão" class="nav-link" data-scroll-target="#intervalo-de-previsão"><span class="header-section-number">8.2</span> Intervalo de Previsão</a>
  <ul class="collapse">
  <li><a href="#interpretações-1" id="toc-interpretações-1" class="nav-link" data-scroll-target="#interpretações-1"><span class="header-section-number">8.2.1</span> Interpretações</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusão" id="toc-conclusão" class="nav-link" data-scroll-target="#conclusão"><span class="header-section-number">9</span> Conclusão</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Relatório: base de dados pinguins</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Ananda Vilar Vidal e José Jardel Alves de Medeiros </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">7 de outubro de 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Setup para o relatório Quarto</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">message =</span> <span class="cn">FALSE</span>, <span class="at">warning =</span> <span class="cn">FALSE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introdução" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introdução</h1>
<p>Este relatório tem por objetivo ajustar um modelo de regressão linear múltiplo com o intuito de explorar a base de dados de <code>pinguins</code> para identificar determinadas características (medidas) associadas a 3 espécies de pinguins sobre a característica <code>profundidade do bico</code> (<code>“profundidade_bico”</code>).</p>
<p>Neste contexto, a regressão será realizada sobre a conhecida base de dados <code>Pinguins</code>, que inclui espécies de pinguins e ilhas do Arquipélago Palmer, as medidas de cada espécie (comprimento da nadadeira, massa corporal e dimensões do bico), o sexo de cada pinguim e ano de documentação.</p>
<p>Aqui estão fotos das espécies de pinguins:</p>
<p><img src="especies_de_pinguins.png" id="fig-especiespinguins" class="img-fluid"> <br></p>
</section>
<section id="os-dados" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Os dados</h1>
<p>É possível baixar os dados da biblioteca <code>dados</code> do <em>R</em>. Apenas carregando a biblioteca, um data frame chamado <code>pinguins</code> fica disponibilizado e poderá ser usado imediatamente. Para a visualização das características dos dados utiliza-se o glimpse da biblioteca <code>dplyr</code>, que informa a quantidade de linhas, colunas e as variáveis. Para ter acesso faça os seguintes passos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dados)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(pinguins)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 344
Columns: 8
$ especie               &lt;fct&gt; Pinguim-de-adélia, Pinguim-de-adélia, Pinguim-de…
$ ilha                  &lt;fct&gt; Torgersen, Torgersen, Torgersen, Torgersen, Torg…
$ comprimento_bico      &lt;dbl&gt; 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34…
$ profundidade_bico     &lt;dbl&gt; 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18…
$ comprimento_nadadeira &lt;int&gt; 181, 186, 195, NA, 193, 190, 181, 195, 193, 190,…
$ massa_corporal        &lt;int&gt; 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 34…
$ sexo                  &lt;fct&gt; macho, fêmea, fêmea, NA, fêmea, macho, fêmea, ma…
$ ano                   &lt;int&gt; 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(pinguins<span class="sc">$</span>especie) <span class="co"># verifica as espécies distintas</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Pinguim-de-adélia   Pinguim-gentoo      Pinguim-de-barbicha
Levels: Pinguim-de-adélia Pinguim-de-barbicha Pinguim-gentoo</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pinguins<span class="sc">$</span>especie) <span class="co"># Frequencias por espécie</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Pinguim-de-adélia Pinguim-de-barbicha      Pinguim-gentoo 
                152                  68                 124 </code></pre>
</div>
</div>
<p>Visualizando rapidamente a estrutura da base de dados, observamos as seguintes variáveis:</p>
<ul>
<li><p><code>especie</code>: espécies de pinguim (Pinguim-de-adélia, Pinguim-de-barbicha e Pinguim-gentoo);</p></li>
<li><p><code>ilha</code>: ilha do Arquipélago Palmer na Antártida (Biscoe, Dream, Togersen);</p></li>
<li><p><code>comprimento_bico</code>: número decimal que indica o comprimento do bico (em milímetros);</p></li>
<li><p><code>profundidade_bico</code>: número decimal que indica a profundidade do bico (em milímetros);</p></li>
<li><p><code>comprimento_nadadeira</code>: número inteiro que indica o comprimento da nadadeira (em milímetros);</p></li>
<li><p><code>massa_corporal</code>: número inteiro que indica a massa corporal (em gramas);</p></li>
<li><p><code>sexo</code>: fator que indica o sexo do(a) pinguim (macho, fêmea);</p></li>
<li><p><code>ano</code>: número inteiro que indica o ano da coleta dos dados (2007, 2008 ou 2009).</p></li>
</ul>
<section id="análise-exploratória-dos-dados" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="análise-exploratória-dos-dados"><span class="header-section-number">2.1</span> Análise exploratória dos dados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> pinguins</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(dados)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">dados</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">344</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">ordered</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: left;">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">especie</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Pin: 152, Pin: 124, Pin: 68</td>
</tr>
<tr class="even">
<td style="text-align: left;">ilha</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Bis: 168, Dre: 124, Tor: 52</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sexo</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">mac: 168, fêm: 165</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">comprimento_bico</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">43.92</td>
<td style="text-align: right;">5.46</td>
<td style="text-align: right;">32.1</td>
<td style="text-align: right;">39.23</td>
<td style="text-align: right;">44.45</td>
<td style="text-align: right;">48.5</td>
<td style="text-align: right;">59.6</td>
<td style="text-align: left;">▃▇▇▆▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">profundidade_bico</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">17.15</td>
<td style="text-align: right;">1.97</td>
<td style="text-align: right;">13.1</td>
<td style="text-align: right;">15.60</td>
<td style="text-align: right;">17.30</td>
<td style="text-align: right;">18.7</td>
<td style="text-align: right;">21.5</td>
<td style="text-align: left;">▅▅▇▇▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">comprimento_nadadeira</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">200.92</td>
<td style="text-align: right;">14.06</td>
<td style="text-align: right;">172.0</td>
<td style="text-align: right;">190.00</td>
<td style="text-align: right;">197.00</td>
<td style="text-align: right;">213.0</td>
<td style="text-align: right;">231.0</td>
<td style="text-align: left;">▂▇▃▅▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">massa_corporal</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">4201.75</td>
<td style="text-align: right;">801.95</td>
<td style="text-align: right;">2700.0</td>
<td style="text-align: right;">3550.00</td>
<td style="text-align: right;">4050.00</td>
<td style="text-align: right;">4750.0</td>
<td style="text-align: right;">6300.0</td>
<td style="text-align: left;">▃▇▆▃▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ano</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2008.03</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">2007.0</td>
<td style="text-align: right;">2007.00</td>
<td style="text-align: right;">2008.00</td>
<td style="text-align: right;">2009.0</td>
<td style="text-align: right;">2009.0</td>
<td style="text-align: left;">▇▁▇▁▇</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Através da visão geral resumida do dataframe gerada pela biblioteca <code>skimr</code> é possível obter um resumo de várias estatísticas descritivas e informações sobre cada coluna do dataframe <code>dados</code> (<code>pinguins</code>).</p>
<p>Pode-se observar que esse conjunto de dados possui 344 linhas e 8 colunas, sendo 3 categóricas e 5 numéricas.</p>
<ul>
<li><p>Resumo das Colunas: cada coluna do dataframe é listada com seu nome e o tipo de dado de cada coluna é mostrado.</p></li>
<li><p>Estatísticas Descritivas: incluem o número de valores (n), média, mediana, mínimo, máximo, desvio padrão e outros quantis (percentis).</p></li>
<li><p>Valores Faltantes: um resumo da quantidade de valores faltantes (NA) para cada coluna.</p></li>
<li><p>Análise de percentil: indica que a maioria dos valores está entre intervalos esperados.</p></li>
<li><p>Distribuição das variáveis numéricas: sugere que os dados estão podem ser utilizados em análises mais profundas, uma vez que aparentam estar razoáveis e consistentes.</p></li>
</ul>
</section>
<section id="análise-de-outliers" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="análise-de-outliers"><span class="header-section-number">2.2</span> Análise de outliers</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(dados<span class="sc">$</span>profundidade_bico,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot profundidade do bico"</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"profundidade_bico"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">border =</span> <span class="st">"darkblue"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">outline =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pinguins_Roteiro_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(dados<span class="sc">$</span>comprimento_bico,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot comprimento do bico"</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"comprimento_bico"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">border =</span> <span class="st">"darkblue"</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">outline =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pinguins_Roteiro_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(dados<span class="sc">$</span>comprimento_nadadeira,</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot comprimento da nadadeira"</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"comprimento_nadadeira"</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">border =</span> <span class="st">"darkblue"</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">outline =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pinguins_Roteiro_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(dados<span class="sc">$</span>massa_corporal,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot massa corporal"</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"massa_corporal"</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">border =</span> <span class="st">"darkblue"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">outline =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pinguins_Roteiro_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Após análise dos boxplot das variáveis, verifica-se que não existem outliers (pontos que ficam fora dos limites dos gráficos). Dessa forma, é possível concluir que os dados estão bem distribuidos dentro do intervalo esperado, com dados bem comportados e sem variabilidade extrema e/ou valores que podem distorcer a análise estatística.</p>
</section>
<section id="sec-GGally" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="sec-GGally"><span class="header-section-number">2.3</span> Análise de correlação</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(profundidade_bico <span class="sc">~</span> comprimento_nadadeira, </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> dados, </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">"Profundidade do bico por comprimento da nadadeira"</span>, </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"comprimento_nadadeira"</span>, <span class="at">ylab =</span> <span class="st">"profundidade_bico"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pinguins_Roteiro_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Analisando o gráfico, pode-se concluir que o coeficiente de correlação linear <em>r</em> será negativo, já que quando o comprimento da nadadeira é maior a profundidade do bico é menor e quando o comprimento da nadadeira é menor a profundidade do bico é maior, sendo inversamente proporcional</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(profundidade_bico <span class="sc">~</span> comprimento_bico, </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> dados, </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">"Profundidade do bico por comprimento do bico"</span>, </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"comprimento_bico"</span>, <span class="at">ylab =</span> <span class="st">"profundidade_bico"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pinguins_Roteiro_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>No gráfico acima não é possível identificar relações entre as variáveis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(profundidade_bico <span class="sc">~</span> massa_corporal, </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> dados, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">"Profundidade do bico por comprimento do bico"</span>, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"massa_corporal"</span>, <span class="at">ylab =</span> <span class="st">"profundidade_bico"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pinguins_Roteiro_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Já no gráfico acima observa-se que quanto maior a massa corporal menor a profundidade do bico e quanto menor a massa corporal maior a profundidade do bico, sendo também inversamente proporcional com correlação linear negativa.</p>
<p>Partimos então para uma análise de correlação das variáveis quantitativas</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)  <span class="co"># Pacote para função ggpairs</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co"># Pacote para salvar gráficos</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="do">### Multicolinearidade: r &gt; 0.9 (ou 0.8)</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>graf1 <span class="ot">&lt;-</span> <span class="fu">ggpairs</span>(pinguins, <span class="at">columns =</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">6</span>, ggplot2<span class="sc">::</span><span class="fu">aes</span>(<span class="at">colour =</span> especie))  <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>),  <span class="co"># diminui o texto no eixo X</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>),  <span class="co"># diminui o texto no eixo Y</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>),   <span class="co"># diminui os rótulos das facetas</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    )   </span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>graf1</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pinguins_Roteiro_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Salvando o gráfico em .jpeg</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"Grafico_dispersao_pinguins.jpeg"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="comentários" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="comentários"><span class="header-section-number">2.3.1</span> Comentários:</h3>
<p>Com relação à análise de correlação é algo desejável observar altas correlações das variáveis independentes com relação à variável dependente/resposta que no presente caso é <code>profundidade do bico</code> (<code>profundidade_bico</code>).</p>
<p>Por outro lado, altas correlações entre as demais variáveis a serem utilizadas como variáveis independentes/preditoras nos dá indícios de que haverá <strong>problemas de multicolinearidade</strong> ao ajustar o MRLM. <strong>Como regra geral</strong> isto ocorre quando há <strong>correlações</strong> <span class="math inline">\(\geq 0.9\)</span> ou <span class="math inline">\(\geq 0.8\)</span> <strong>entre</strong> as <strong>variáveis preditoras</strong>.</p>
<p>Dito isto, é possível observar que:</p>
<ol type="1">
<li>A variável dependente <code>profundidade_bico</code>:</li>
</ol>
<!-- -->
<ol type="i">
<li>apresenta correlação linear significante com a variável <code>comprimento_bico</code> (r= -0.235, p &lt; 0.001);</li>
</ol>
<p>Como esta correlação, em valor absoluto não é superior a 0.9 (ou 0.8) não há indício para um posterior problema de multicolinearidade.</p>
<ol start="2" type="i">
<li>apresenta correlação linear significante com a variável <code>comprimento_nadadeira</code> (r= -0.584, p &lt; 0.001);</li>
</ol>
<p>Como esta correlação, em valor absoluto não é superior a 0.9 (ou 0.8) não há indício para um posterior problema de multicolinearidade.</p>
<ol start="3" type="i">
<li>apresenta correlação linear significante com a variável <code>massa_corporal</code> (r= -0.472, p &lt; 0.001);</li>
</ol>
<!-- -->
<ol start="2" type="1">
<li>A variável independente <code>comprimento_bico</code>:</li>
</ol>
<!-- -->
<ol type="i">
<li>apresenta correlação linear significativa com a variável <em>independente</em> <code>comprimento_nadadeira</code> (r=0.656, p &lt; 0.001).</li>
</ol>
<p>Como esta correlação, em valor absoluto não é superior a 0.9 (ou 0.8) não há indício para um posterior problema de multicolinearidade.</p>
<ol start="2" type="i">
<li>apresenta correlação linear significativa com a variável <em>independente</em> <code>massa_corporal</code> (r=0.595, p &lt; 0.001).</li>
</ol>
<p>Como esta correlação, em valor absoluto não é superior a 0.9 (ou 0.8) não há indício para um posterior problema de multicolinearidade.</p>
<!-- -->
<ol start="3" type="1">
<li>A variável independente <code>comprimento_nadadeira</code>:</li>
</ol>
<!-- -->
<ol type="i">
<li>apresenta correlação linear significativa com a variável <em>independente</em> <code>massa_corporal</code> (r=0.871, p &lt; 0.001).</li>
</ol>
<!-- -->
<p>Como esta correlação, em valor absoluto é superior a 0.8 <strong>há indício</strong> para um posterior <strong>problema de multicolinearidade</strong>. Observa-se, ainda, que tal correlação é do tipo forte e positiva, ou seja, <strong>as medidas</strong> associadas aos <strong>pinguins</strong> se relacionam de forma <strong>fortemente positiva</strong>.</p>
</section>
<section id="analisando-o-vif" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="analisando-o-vif"><span class="header-section-number">2.3.2</span> Analisando o VIF</h3>
<p>O Fator de Inflação de Variância (VIF) é uma forma de identificar multicolinearidade.</p>
<p>Para investigar mais sobre multicolinearidade, sugerimos a leitura do seguinte material: <a href="https://www.statology.org/multicollinearity-regression/" class="uri">https://www.statology.org/multicollinearity-regression/</a></p>
<p>O VIF é calculado da seguinte forma:</p>
<p>Para cada variável independente faz-se uma regressão linear dessa variável para todas as outras variáveis independentes, obtendo o <span class="math inline">\(R^2\)</span> dessa regressão.</p>
<p>Com o <span class="math inline">\(R^2\)</span>, o VIF = 1/(1 - <span class="math inline">\(R^2\)</span>)</p>
<p>Por convenção, um VIF &gt; 10 indica um problema de multicolinearidade.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Modelo inicial com todas as variáveis</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>modelo1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(profundidade_bico <span class="sc">~</span> comprimento_bico <span class="sc">+</span> massa_corporal <span class="sc">+</span> comprimento_nadadeira <span class="sc">+</span> sexo <span class="sc">+</span> ano <span class="sc">+</span> ilha <span class="sc">+</span> especie, <span class="at">data =</span> pinguins)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car) </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(modelo1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                           GVIF Df GVIF^(1/(2*Df))
comprimento_bico       6.167650  1        2.483475
massa_corporal         7.892055  1        2.809280
comprimento_nadadeira  8.377861  1        2.894453
sexo                   2.483368  1        1.575871
ano                    1.163562  1        1.078685
ilha                   3.756428  2        1.392175
especie               45.302557  2        2.594363</code></pre>
</div>
</div>
<p>Como pode-se observar, a variável especie possui um VIF de aproximadamente 45, por ser maior que 10, há um problema de multicolinearidade.</p>
</section>
</section>
</section>
<section id="modelos" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Modelos</h1>
<section id="modelo-1-com-todas-as-variáveis-independentes." class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="modelo-1-com-todas-as-variáveis-independentes."><span class="header-section-number">3.1</span> Modelo 1: Com todas as variáveis independentes.</h2>
<p>Como vimos anteriormente, o modelo 1 se dá com todas as variáveis disponíveis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = profundidade_bico ~ comprimento_bico + massa_corporal + 
    comprimento_nadadeira + sexo + ano + ilha + especie, data = pinguins)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.02812 -0.53903  0.00004  0.43546  2.71777 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 3.095e+02  1.144e+02   2.706  0.00718 ** 
comprimento_bico            4.110e-02  1.959e-02   2.098  0.03665 *  
massa_corporal              4.574e-04  1.505e-04   3.040  0.00256 ** 
comprimento_nadadeira       2.705e-02  8.907e-03   3.037  0.00258 ** 
sexomacho                   8.632e-01  1.357e-01   6.359 6.91e-10 ***
ano                        -1.494e-01  5.723e-02  -2.610  0.00948 ** 
ilhaDream                  -1.641e-01  1.599e-01  -1.026  0.30567    
ilhaTorgersen              -3.508e-03  1.671e-01  -0.021  0.98327    
especiePinguim-de-barbicha -4.166e-01  2.462e-01  -1.692  0.09163 .  
especiePinguim-gentoo      -5.150e+00  3.059e-01 -16.834  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7859 on 323 degrees of freedom
  (11 observations deleted due to missingness)
Multiple R-squared:  0.8451,    Adjusted R-squared:  0.8407 
F-statistic: 195.7 on 9 and 323 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Ao observar os dados, percebe-se uma contradição no que se diz respeito as variáveis comprimento_bico, massa_corporal e comprimento_nadadeira, uma vez que os coeficientes de Pearson de cada são negativos, mas as estimativas dos mesmos são positivos.</p>
</section>
<section id="modelo-2-sem-a-variável-espécie." class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="modelo-2-sem-a-variável-espécie."><span class="header-section-number">3.2</span> Modelo 2: Sem a variável espécie.</h2>
<p>Por a variável espécie possuir um VIF elevado, vamos montar nosso modelo 2 sem a mesma.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>modelo2 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1, <span class="sc">~</span> . <span class="sc">-</span>especie)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo2)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = profundidade_bico ~ comprimento_bico + massa_corporal + 
    comprimento_nadadeira + sexo + ano + ilha, data = pinguins)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.7329 -0.7450 -0.1286  0.6913  4.4479 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           -1.124e+02  1.550e+02  -0.725  0.46888    
comprimento_bico       9.445e-03  1.680e-02   0.562  0.57446    
massa_corporal        -5.304e-04  1.885e-04  -2.814  0.00518 ** 
comprimento_nadadeira -5.480e-02  1.057e-02  -5.184 3.82e-07 ***
sexomacho              2.194e+00  1.486e-01  14.766  &lt; 2e-16 ***
ano                    7.010e-02  7.738e-02   0.906  0.36567    
ilhaDream              1.032e+00  1.849e-01   5.584 4.97e-08 ***
ilhaTorgersen          1.127e+00  2.150e-01   5.239 2.91e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.095 on 325 degrees of freedom
  (11 observations deleted due to missingness)
Multiple R-squared:  0.697, Adjusted R-squared:  0.6905 
F-statistic: 106.8 on 7 and 325 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Observando os dados, percebe-se que a variável <code>comprimento_bico</code> ainda continua contraditória, uma vez que sua estimativa é positiva e o Coeficiente de Pearson negativa. Ademais, o seu valor p é de aproximadamente 0.57, ou seja, não é significativo.</p>
<p>Além da variável <code>comprimento_bico</code>, a variável <code>ano</code>apresenta um valor p &gt; 0.1, alto o suficiente para não ser significante.</p>
<p>Vale ressaltar que o R ajustado desse modelo é de 0.6905, então 69,05% das variações de <code>profundidade_bico</code>` estão sendo explicadas pelo modelo.</p>
</section>
<section id="modelo-3-sem-as-variáveis-especie-e-ano." class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="modelo-3-sem-as-variáveis-especie-e-ano."><span class="header-section-number">3.3</span> Modelo 3: Sem as variáveis especie e ano.</h2>
<p>Então, construimos um terceiro modelo, dessa vez retirando não só a variável <code>espécie</code>, mas também a variável <code>ano</code>. De início, não retiremos a <code>comprimento_bico</code> para analisar seu comportamento, como também das demais variáveis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>modelo3 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo2, <span class="sc">~</span> . <span class="sc">-</span>ano)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo3)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = profundidade_bico ~ comprimento_bico + massa_corporal + 
    comprimento_nadadeira + sexo + ilha, data = pinguins)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.6652 -0.7570 -0.0978  0.6691  4.5297 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           28.0101282  1.3710360  20.430  &lt; 2e-16 ***
comprimento_bico       0.0081433  0.0167377   0.487   0.6269    
massa_corporal        -0.0005690  0.0001835  -3.100   0.0021 ** 
comprimento_nadadeira -0.0520587  0.0101260  -5.141 4.72e-07 ***
sexomacho              2.2059792  0.1480103  14.904  &lt; 2e-16 ***
ilhaDream              1.0307490  0.1848251   5.577 5.15e-08 ***
ilhaTorgersen          1.1245487  0.2149605   5.231 3.02e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.095 on 326 degrees of freedom
  (11 observations deleted due to missingness)
Multiple R-squared:  0.6963,    Adjusted R-squared:  0.6907 
F-statistic: 124.6 on 6 and 326 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>O modelo 3 apresenta que a varriável <code>comprimento_bico</code> apesar de ter diminuido seu estimador, continua positivo contrariando o Coeficiente de Pearson, além do seu alto valor p.</p>
<p>O R ajustado é de 0.6907, então 69,07% das variações de <code>profundidade_bico</code>estão sendo explicadas pelo modelo, apesar de mínimo, houve um aumento em relação com o anterior.</p>
</section>
<section id="modelo-4-sem-as-variáveis-espécie-ano-e-comprimento_bico." class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="modelo-4-sem-as-variáveis-espécie-ano-e-comprimento_bico."><span class="header-section-number">3.4</span> Modelo 4: Sem as variáveis espécie, ano e comprimento_bico.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>modelo4 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo3, <span class="sc">~</span>. <span class="sc">-</span>comprimento_bico)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo4)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = profundidade_bico ~ massa_corporal + comprimento_nadadeira + 
    sexo + ilha, data = pinguins)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.6861 -0.7580 -0.0936  0.6901  4.5334 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           27.9043913  1.3521204  20.638  &lt; 2e-16 ***
massa_corporal        -0.0005633  0.0001829  -3.079  0.00225 ** 
comprimento_nadadeira -0.0499521  0.0091429  -5.464 9.26e-08 ***
sexomacho              2.2176123  0.1458956  15.200  &lt; 2e-16 ***
ilhaDream              1.0626246  0.1726214   6.156 2.19e-09 ***
ilhaTorgersen          1.1179289  0.2142790   5.217 3.23e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.094 on 327 degrees of freedom
  (11 observations deleted due to missingness)
Multiple R-squared:  0.6961,    Adjusted R-squared:  0.6914 
F-statistic: 149.8 on 5 and 327 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Este modelo 4 por sua vez apresenta coerência nos estimadores das variáveis analisadas na Análise Exploratória com seus respectivos Coeficientes de Pearson. Além do mais, ao observar o valor p, todas as variáveis apresentam significância.</p>
<p>Observa-se que o R ajustado é de 0.6914, ou seja, o 69,14% das variáções de `profundidade_bico` estão sendo explicadas pelo modelo.</p>
<p>É importante destacar que o R ajustado do modelo 4 em relação aos outros modelos aumentou minimamente, porém ainda continua sendo o modelo, dos que não possuem problema de multicolinearidade, que mais explica <code>profundidade_bico</code>`.</p>
</section>
</section>
<section id="métodos-para-selecionar-o-melhor-modelo." class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Métodos para selecionar o melhor modelo.</h1>
<p>Por existir problema de multicolinearidade no modelo 1, ele não é considerado na seleção.</p>
<section id="medida-aic" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="medida-aic"><span class="header-section-number">4.1</span> Medida AIC</h2>
<p>A medida AIC determina que o melhor modelo é o que apresenta o menor valor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo2)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1015.66</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo3)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1014.499</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo4)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1012.741</code></pre>
</div>
</div>
<p>Apesar de bem próximos e pela regra não há um indício significativo de real diferença, uma vez que a diferença entre os modelos não é maior que 10. O modelo 4 ainda é preferível aos demais por ser o menor.</p>
</section>
<section id="medida-bic" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="medida-bic"><span class="header-section-number">4.2</span> Medida BIC</h2>
<p>Analogamente ao AIC, a medida BIC determina que o melhor modelo é aquele que apresentar menor valor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(modelo2)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1049.933</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(modelo3)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1044.964</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(modelo4)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1039.398</code></pre>
</div>
</div>
<p>O modelo 4 apresenta uma diferença maior que 10 ao modelo 2, então há um indício de real diferença entre modelos. Embora essa diferença não ocorra entre os modelos 3 e 4, o modelo 4 é menor, e portanto, preferível.</p>
</section>
<section id="comparação-de-modelos-encaixados-anova" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="comparação-de-modelos-encaixados-anova"><span class="header-section-number">4.3</span> Comparação de modelos encaixados (ANOVA)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo2, modelo3)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: profundidade_bico ~ comprimento_bico + massa_corporal + comprimento_nadadeira + 
    sexo + ano + ilha
Model 2: profundidade_bico ~ comprimento_bico + massa_corporal + comprimento_nadadeira + 
    sexo + ilha
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1    325 390.04                           
2    326 391.02 -1  -0.98484 0.8206 0.3657</code></pre>
</div>
</div>
<p>Observa-se que pelo teste F não deve rejeitar a hipótese nula, logo a remoção da variável <code>ano</code> não melhora significamente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo2, modelo4)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: profundidade_bico ~ comprimento_bico + massa_corporal + comprimento_nadadeira + 
    sexo + ano + ilha
Model 2: profundidade_bico ~ massa_corporal + comprimento_nadadeira + 
    sexo + ilha
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1    325 390.04                           
2    327 391.31 -2   -1.2688 0.5286 0.5899</code></pre>
</div>
</div>
<p>Observa-se que pelo teste F não deve rejeitar a hipótese nula, logo a remoção da variável <code>ano</code> e da <code>comprimento_bico</code> não melhora significamente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo3, modelo4)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: profundidade_bico ~ comprimento_bico + massa_corporal + comprimento_nadadeira + 
    sexo + ilha
Model 2: profundidade_bico ~ massa_corporal + comprimento_nadadeira + 
    sexo + ilha
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1    326 391.02                           
2    327 391.31 -1  -0.28392 0.2367 0.6269</code></pre>
</div>
</div>
<p>Observa-se que pelo teste F não deve rejeitar a hipótese nula, logo a remoção da variável <code>comprimento_bico</code> não melhora significamente.</p>
</section>
</section>
<section id="seleção-automática" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Seleção automática</h1>
<section id="a-partir-do-modelo-1" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="a-partir-do-modelo-1"><span class="header-section-number">5.1</span> A partir do modelo 1</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(modelo1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-150.62
profundidade_bico ~ comprimento_bico + massa_corporal + comprimento_nadadeira + 
    sexo + ano + ilha + especie

                        Df Sum of Sq    RSS      AIC
- ilha                   2     0.898 200.39 -153.130
&lt;none&gt;                               199.49 -150.625
- comprimento_bico       1     2.719 202.21 -148.116
- ano                    1     4.207 203.70 -145.675
- comprimento_nadadeira  1     5.698 205.19 -143.247
- massa_corporal         1     5.706 205.19 -143.234
- sexo                   1    24.977 224.47 -113.342
- especie                2   190.548 390.04   68.646

Step:  AIC=-153.13
profundidade_bico ~ comprimento_bico + massa_corporal + comprimento_nadadeira + 
    sexo + ano + especie

                        Df Sum of Sq    RSS     AIC
&lt;none&gt;                               200.39 -153.13
- comprimento_bico       1     2.959 203.35 -150.25
- ano                    1     4.181 204.57 -148.25
- massa_corporal         1     5.731 206.12 -145.74
- comprimento_nadadeira  1     5.825 206.21 -145.59
- sexo                   1    24.644 225.03 -116.51
- especie                2   237.085 437.47  102.86</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = profundidade_bico ~ comprimento_bico + massa_corporal + 
    comprimento_nadadeira + sexo + ano + especie, data = pinguins)

Coefficients:
               (Intercept)            comprimento_bico  
                 3.071e+02                   4.277e-02  
            massa_corporal       comprimento_nadadeira  
                 4.577e-04                   2.700e-02  
                 sexomacho                         ano  
                 8.562e-01                  -1.483e-01  
especiePinguim-de-barbicha       especiePinguim-gentoo  
                -5.340e-01                  -5.101e+00  </code></pre>
</div>
</div>
<p>Pela seleção automática, a partir do modelo 1, observa-se que o melhor modelo seria o modelo 1. Porém, como observado anteriormente, este modelo possui problema de multicolinearidade e por isso, não deve ser considerado e a seleção automática não deve levar em consideração a variável <code>especie</code>.</p>
</section>
<section id="a-partir-do-modelo-2" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="a-partir-do-modelo-2"><span class="header-section-number">5.2</span> A partir do modelo 2</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(modelo2)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=68.65
profundidade_bico ~ comprimento_bico + massa_corporal + comprimento_nadadeira + 
    sexo + ano + ilha

                        Df Sum of Sq    RSS     AIC
- comprimento_bico       1     0.379 390.42  66.970
- ano                    1     0.985 391.02  67.486
&lt;none&gt;                               390.04  68.646
- massa_corporal         1     9.506 399.54  74.665
- comprimento_nadadeira  1    32.254 422.29  93.104
- ilha                   2    47.435 437.47 102.865
- sexo                   1   261.659 651.70 237.588

Step:  AIC=66.97
profundidade_bico ~ massa_corporal + comprimento_nadadeira + 
    sexo + ano + ilha

                        Df Sum of Sq    RSS     AIC
- ano                    1     0.890 391.31  65.728
&lt;none&gt;                               390.42  66.970
- massa_corporal         1     9.362 399.78  72.861
- comprimento_nadadeira  1    36.047 426.46  94.378
- ilha                   2    51.639 442.05 104.336
- sexo                   1   272.685 663.10 241.365

Step:  AIC=65.73
profundidade_bico ~ massa_corporal + comprimento_nadadeira + 
    sexo + ilha

                        Df Sum of Sq    RSS     AIC
&lt;none&gt;                               391.31  65.728
- massa_corporal         1    11.347 402.65  73.247
- comprimento_nadadeira  1    35.720 427.03  92.817
- ilha                   2    51.248 442.55 102.711
- sexo                   1   276.474 667.78 241.706</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = profundidade_bico ~ massa_corporal + comprimento_nadadeira + 
    sexo + ilha, data = pinguins)

Coefficients:
          (Intercept)         massa_corporal  comprimento_nadadeira  
           27.9043913             -0.0005633             -0.0499521  
            sexomacho              ilhaDream          ilhaTorgersen  
            2.2176123              1.0626246              1.1179289  </code></pre>
</div>
</div>
<p>Como pode ser observado, o modelo 4 foi o selecionado.</p>
</section>
</section>
<section id="modelo-selecionado-modelo4" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Modelo selecionado (modelo4)</h1>
<p>A partir das analises feitas até o momento e tendo como objetivo realizar previsões e as interpretá-las, como também verificar os pressupostos do Modelo de Regressão Linear Múltipla (MRLM) o modelo selecionado é o modelo 4.</p>
<section id="verificando-os-pressupostos-do-mrlm" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="verificando-os-pressupostos-do-mrlm"><span class="header-section-number">6.1</span> Verificando os pressupostos do MRLM</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo4)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pinguins_Roteiro_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pinguins_Roteiro_files/figure-html/unnamed-chunk-23-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pinguins_Roteiro_files/figure-html/unnamed-chunk-23-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pinguins_Roteiro_files/figure-html/unnamed-chunk-23-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="análise-dos-pressupostos" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="análise-dos-pressupostos"><span class="header-section-number">6.1.1</span> Análise dos pressupostos</h3>
<ul>
<li>Residuals x Fitted: Pode-se perceber que a linha vermelha não fere a homocedasticidade, uma vez que não apresenta uma inclinação significante, exibindo então, uma variância constante dos erros/resíduos.</li>
<li>Q-Q Residuals: O gráfico apresenta que a grande maioria dos pontos segue distribuição normal, visto que os mesmos estão alinhados com a reta.</li>
<li>Scale-Location: Apresenta uma leve inclinação crescente, porém não o suficiente para indicar heterocedasticidade.</li>
<li>Residuals x Leverage: Pode-se observar que o ponto 115 é um outlier.</li>
</ul>
<p>O Leverage evidencia que o 115 é um outlier, porém ele esteve destacado dos demais nos outros três gráficos também. Então, uma possível abordagem futura seria retirar o ponto 115, já que ele é um outlier, e observar como os pontos se comportam.</p>
</section>
</section>
</section>
<section id="interpretações-do-modelo-selecionado" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Interpretações do modelo selecionado</h1>
<p>Ajustamos um modelo linear (estimado utilizando Mínimos Quadrados Ordinários, OLS) para prever a profundidade do bico dos pinguins com base nas variáveis massa corporal, comprimento da nadadeira, sexo e ilha (fórmula: profundidade_bico ~ massa_corporal + comprimento_nadadeira + sexo + ilha). O modelo explica uma proporção significativa e substancial da variância observada (R² = 0,70, F(5, 327) = 149,78, p &lt; 0,001; R² ajustado = 0,69).</p>
<ul>
<li>Intercepto: O intercepto, que corresponde ao cenário em que massa_corporal = 0, comprimento_nadadeira = 0, sexo = fêmea e ilha = Biscoe, tem um valor estimado de 27,90 (IC 95% [25,24, 30,56], t(327) = 20,64, p &lt; 0,001). Isso significa que, para um pinguim fêmea da ilha Biscoe com massa corporal e comprimento da nadadeira nulos (cenário teórico), a profundidade média do bico seria de aproximadamente 27,90 mm.</li>
<li>Massa Corporal: O efeito da massa corporal é estatisticamente significativo e negativo (beta = -0,000563, IC 95% [-0,000923, -0,000203], t(327) = -3,08, p = 0,002; beta padronizado = -0,23, IC 95% [-0,38, -0,08]). Em termos práticos, isso significa que, para cada aumento de 1 grama na massa corporal, a profundidade do bico diminui, em média, cerca de 0,000563 mm. O efeito é relativamente pequeno, mas estatisticamente significativo, sugerindo que pinguins mais pesados tendem a ter bicos ligeiramente menos profundos.</li>
<li>Comprimento da Nadadeira: O efeito do comprimento da nadadeira também é estatisticamente significativo e negativo (beta = -0,05, IC 95% [-0,07, -0,03], t(327) = -5,46, p &lt; 0,001; beta padronizado = -0,36, IC 95% [-0,48, -0,23]). Para cada aumento de 1 mm no comprimento da nadadeira, a profundidade do bico diminui, em média, 0,05 mm. Esse efeito sugere que pinguins com nadadeiras mais longas tendem a ter bicos menos profundos.</li>
<li>Sexo (Macho): O efeito do sexo, comparando machos a fêmeas, é positivo e estatisticamente significativo (beta = 2,22, IC 95% [1,93, 2,50], t(327) = 15,20, p &lt; 0,001; beta padronizado = 1,13, IC 95% [0,98, 1,27]). Isso significa que, em média, os pinguins machos têm bicos 2,22 mm mais profundos do que as fêmeas, controlando pelas outras variáveis. Este é um dos efeitos mais fortes no modelo, sugerindo que o sexo é um fator importante para prever a profundidade do bico.</li>
<li>Ilha (Dream): O efeito de ser da ilha Dream, comparado a ser da ilha Biscoe, é positivo e estatisticamente significativo (beta = 1,06, IC 95% [0,72, 1,40], t(327) = 6,16, p &lt; 0,001; beta padronizado = 0,54, IC 95% [0,37, 0,71]). Isso indica que os pinguins da ilha Dream tendem a ter bicos, em média, 1,06 mm mais profundos do que os da ilha Biscoe.</li>
<li>Ilha (Torgersen): O efeito de ser da ilha Torgersen, comparado a ser da ilha Biscoe, também é positivo e estatisticamente significativo (beta = 1,12, IC 95% [0,70, 1,54], t(327) = 5,22, p &lt; 0,001; beta padronizado = 0,57, IC 95% [0,35, 0,78]). Isso significa que os pinguins da ilha Torgersen tendem a ter bicos, em média, 1,12 mm mais profundos do que os da ilha Biscoe.</li>
</ul>
<p>O modelo mostra que as variáveis massa corporal, comprimento da nadadeira, sexo e ilha têm efeitos significativos na profundidade do bico dos pinguins. Pinguins mais pesados e com nadadeiras mais longas tendem a ter bicos menos profundos, enquanto os machos, e aqueles das ilhas Dream e Torgersen, têm bicos mais profundos. O sexo parece ser o fator mais relevante, seguido pela localização geográfica (ilha), enquanto as medidas físicas (massa corporal e comprimento da nadadeira) também contribuem, mas em menor grau.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(report)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(modelo4)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a linear model (estimated using OLS) to predict profundidade_bico
with massa_corporal, comprimento_nadadeira, sexo and ilha (formula:
profundidade_bico ~ massa_corporal + comprimento_nadadeira + sexo + ilha). The
model explains a statistically significant and substantial proportion of
variance (R2 = 0.70, F(5, 327) = 149.78, p &lt; .001, adj. R2 = 0.69). The model's
intercept, corresponding to massa_corporal = 0, comprimento_nadadeira = 0, sexo
= fêmea and ilha = Biscoe, is at 27.90 (95% CI [25.24, 30.56], t(327) = 20.64,
p &lt; .001). Within this model:

  - The effect of massa corporal is statistically significant and negative (beta
= -5.63e-04, 95% CI [-9.23e-04, -2.03e-04], t(327) = -3.08, p = 0.002; Std.
beta = -0.23, 95% CI [-0.38, -0.08])
  - The effect of comprimento nadadeira is statistically significant and negative
(beta = -0.05, 95% CI [-0.07, -0.03], t(327) = -5.46, p &lt; .001; Std. beta =
-0.36, 95% CI [-0.48, -0.23])
  - The effect of sexo [macho] is statistically significant and positive (beta =
2.22, 95% CI [1.93, 2.50], t(327) = 15.20, p &lt; .001; Std. beta = 1.13, 95% CI
[0.98, 1.27])
  - The effect of ilha [Dream] is statistically significant and positive (beta =
1.06, 95% CI [0.72, 1.40], t(327) = 6.16, p &lt; .001; Std. beta = 0.54, 95% CI
[0.37, 0.71])
  - The effect of ilha [Torgersen] is statistically significant and positive
(beta = 1.12, 95% CI [0.70, 1.54], t(327) = 5.22, p &lt; .001; Std. beta = 0.57,
95% CI [0.35, 0.78])

Standardized parameters were obtained by fitting the model on a standardized
version of the dataset. 95% Confidence Intervals (CIs) and p-values were
computed using a Wald t-distribution approximation.</code></pre>
</div>
</div>
<section id="coeficientes-padronizados" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="coeficientes-padronizados"><span class="header-section-number">7.1</span> Coeficientes padronizados</h2>
<p>Para efeito de comparação dos coeficientes associados a cada variável independente e observação da importância das mesmas, torna-se necessário obter os <strong>coeficientes padronizados</strong>, principalmente quando as unidades de medida tem uma diferença considerável de magnitude.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#obtendo os coeficientes padronizados</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>lm.beta<span class="sc">::</span><span class="fu">lm.beta</span>(modelo4)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = profundidade_bico ~ massa_corporal + comprimento_nadadeira + 
    sexo + ilha, data = pinguins)

Standardized Coefficients::
          (Intercept)        massa_corporal comprimento_nadadeira 
                   NA            -0.2303366            -0.3555274 
            sexomacho             ilhaDream         ilhaTorgersen 
            0.5638887             0.2608274             0.1979508 </code></pre>
</div>
</div>
</section>
</section>
<section id="previsões" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Previsões</h1>
<p>Para uma boa previsão ser realizadas, os valores de cada variável independente deve estar dentro do seu respectivo intevalo observado, uma vez que valores fora desse intervalo, não seriam coerentes com o modelo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#obtendo os intervalos das variáveis </span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                especie           ilha     comprimento_bico profundidade_bico
 Pinguim-de-adélia  :152   Biscoe   :168   Min.   :32.10    Min.   :13.10    
 Pinguim-de-barbicha: 68   Dream    :124   1st Qu.:39.23    1st Qu.:15.60    
 Pinguim-gentoo     :124   Torgersen: 52   Median :44.45    Median :17.30    
                                           Mean   :43.92    Mean   :17.15    
                                           3rd Qu.:48.50    3rd Qu.:18.70    
                                           Max.   :59.60    Max.   :21.50    
                                           NA's   :2        NA's   :2        
 comprimento_nadadeira massa_corporal    sexo          ano      
 Min.   :172.0         Min.   :2700   fêmea:165   Min.   :2007  
 1st Qu.:190.0         1st Qu.:3550   macho:168   1st Qu.:2007  
 Median :197.0         Median :4050   NA's : 11   Median :2008  
 Mean   :200.9         Mean   :4202               Mean   :2008  
 3rd Qu.:213.0         3rd Qu.:4750               3rd Qu.:2009  
 Max.   :231.0         Max.   :6300               Max.   :2009  
 NA's   :2             NA's   :2                                </code></pre>
</div>
</div>
<p>Vamos então criar alguns dados fictícos dentro do intervalo de cada variável preditora baseado nos seus intervalos.</p>
<p>Para então fazer tanto o intervalo de confiança, quanto o intervalo de predição, iremos simular dois pinguins baseados no resumo obtido ds dados. São eles:</p>
<p>Pinguim 1:</p>
<ul>
<li><p>Comprimento de nadadeira: 200.9 mm</p></li>
<li><p>Massa corporal: 4202 g</p></li>
<li><p>Sexo: Macho</p></li>
<li><p>Ilha: Biscoe</p></li>
</ul>
<p>Pinguim 2:</p>
<ul>
<li><p>Comprimento de nadadeira: 200 mm</p></li>
<li><p>Massa corporal: 4100g</p></li>
<li><p>Sexo: Fêmea</p></li>
<li><p>Ilha: Dream</p></li>
</ul>
<p>Antes de prosseguir, perceba que o pinguim 1 obtém dados de cada variável preditora que é exatamente a média obtida das mesmas dos dados que estamos observando</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>dados_previsoes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">comprimento_nadadeira =</span> <span class="fu">c</span>(<span class="fl">200.9</span>, <span class="fl">200.0</span>), <span class="at">massa_corporal =</span> <span class="fu">c</span>(<span class="fl">4202.0</span>, <span class="fl">4100.0</span>), <span class="at">sexo =</span> <span class="fu">c</span>(<span class="st">'macho'</span>, <span class="st">'fêmea'</span>), <span class="at">ilha =</span> <span class="fu">c</span>(<span class="st">'Biscoe'</span>, <span class="st">'Dream'</span>))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="intervalo-de-confiança" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="intervalo-de-confiança"><span class="header-section-number">8.1</span> Intervalo de Confiança</h2>
<p>O intervalo de confiança indica a faixa onde se espera que a média das previsões esteja, dado o modelo ajustado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(modelo4, dados_previsoes, <span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 17.71959 17.44051 17.99867
2 16.66702 16.38806 16.94597</code></pre>
</div>
</div>
<p>Para o pinguim 1, o valor previsto (fit) é de 17.71959 O intervalo de confiança vai de 17.44051 a 17.99867, ou seja, estamos 95% confiantes de que a média da profundidade do bico para um grupo de pinguins com essas características está dentro desse intervalo. É interessante notar que a média de <code>profundidade_bico</code> não está contida nesse intervalo.</p>
<p>Para o segundo pinguim, o valor previsto (fit) é de 16.66702. O intervalo de confiança vai de 16.38806 a 16.94597, indicando que a média prevista para essa combinação de características está nesse intervalo, com 95% de confiança.</p>
<section id="interpretações" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="interpretações"><span class="header-section-number">8.1.1</span> Interpretações</h3>
<p>O fato de o pinguim 1 ter valores das variáveis preditoras sendo exatamente a média de cada variável dos dados e o intervalo de confiança feito a partir dele e do modelo não conterem a média de <code>profundidade_bico</code>`, embora por muito pouco, demonstra que o modelo não explica totalmente os dados, podendo cometer erros, mesmo que mínimos. O que já é esperado uma vez que o modelo explica aproximadamente 70% dos dados.</p>
</section>
</section>
<section id="intervalo-de-previsão" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="intervalo-de-previsão"><span class="header-section-number">8.2</span> Intervalo de Previsão</h2>
<p>O intervalo de previsão é mais largo, pois indica onde se espera que valores individuais de novas observações possam cair, considerando a incerteza do modelo e a variabilidade dos dados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(modelo4, dados_previsoes, <span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 17.71959 15.54957 19.88961
2 16.66702 14.49701 18.83702</code></pre>
</div>
</div>
<p>Para o primeiro o pinguim 1, o valor previsto (fit) é 17.71959, mas o intervalo de previsão vai de 15.54957 a 19.88961, o que reflete a incerteza sobre onde exatamente a profundidade do bico de um pinguim individual com essas características pode estar.</p>
<p>Para o segundo pinguim, o valor previsto (fit) é 16.66702, e o intervalo de previsão vai de 14.49701 a 18.83702, ou seja, a profundidade do bico para um pinguim individual pode cair em qualquer ponto dentro dessa faixa.</p>
<section id="interpretações-1" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="interpretações-1"><span class="header-section-number">8.2.1</span> Interpretações</h3>
<p>O intervalo de previsão demonstra uma variedade dos valores de <code>profundidade_bico</code>, já que é mais amplo e indica a incerteza de onde o valor de <code>profundidade_bico</code> irá estar.</p>
</section>
</section>
</section>
<section id="conclusão" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Conclusão</h1>
<p>O modelo ajustado não apresenta violações dos pressupostos do Modelo de Regressão Linear Múltipla (MRLM) e exibe uma boa capacidade explicativa da variável dependente, com um R ajustado em torno de 70%. Isso reflete uma boa capacidade de explicação da variabilidade da variável dependente pelas variáveis preditoras incluídas no modelo, o que sugere que ele está bem calibrado para os dados analisados.</p>
<p>Contudo, é importante ressaltar que o modelo ainda está sujeito a erros, mesmo que mínimos. Esses erros podem decorrer de diversos fatores, como a presença de variáveis preditoras não incluídas que poderiam melhorar a precisão ou a ausência de um volume de dados suficiente para capturar plenamente a complexidade do fenômeno em análise. Além disso, a qualidade e representatividade dos dados disponíveis podem impactar o desempenho do modelo, limitando seu potencial de generalização para novos conjuntos de dados ou cenários diferentes. Assim, uma coleta mais ampla de dados ou a inclusão de novas variáveis relevantes poderiam contribuir para refinar o modelo e melhorar sua precisão preditiva.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>